### PR TITLE
Updated backend merge

### PR DESCRIPTION
**Pull request by tg1702**
Fixed a few errors with summarisation route.
Changed ChatCompletions -> chat.completions (updated version of OpenAI api)
Changed request.body -> request.data.decode('utf-8')

### CODE REVIEW

**Review by aquonbovell — APPROVED** [review]
I approve the following changes

**Review by aquonbovell — APPROVED** [review]
I approve the following changes

**Review by PeripheralSheep — APPROVED** [review]
Looks fine to me

**Review by aquonbovell — APPROVED** [review]
I have reviewed the changes and approved the request.

**Pull request merged**
